name: AbsorptionShields
version: ${project.version}
website: http://robomwm.com
author: RoboMWM
main: com.robomwm.absorptionshields.AbsorptionShields
softdepend:
- CrackShot
- ExtraHardMode
- MLGDamageIndicators
commands:
  createshield:
      description: Converts the item you are holding into a shield
      permission: absorptionshields.createshield
      permission-message: Hmm, this command isn't for you.
  addlore:
      description: Adds lore to a shield item
      permission: absorptionshields.createshield
      permission-message: Hmm, this command isn't for you.
permissions:
    absorptionshields.*:
        description: Grants ALL THE THINGS
        children:
            absorptionshields.createshield: true
    absorptionshields.createshield:
        description: Permission to /createshield
        default: op
        