name: AbsorptionShields
version: ${project.version}-${git.commit.id.abbrev}
website: http://robomwm.com
author: RoboMWM
main: com.robomwm.absorptionshields.AbsorptionShields
api-version: 1.15
softdepend:
- CrackShot
- ExtraHardMode
- MLGDamageIndicators
- CustomItemRegistry
commands:
  addshieldstats:
      description: Gives you the specified shield
      permission: absorptionshields.addshieldstats
      permission-message: Hmm, this command isn't for you.
permissions:
    absorptionshields.*:
        description: Grants ALL THE THINGS
        children:
            absorptionshields.addshieldstats: true
    absorptionshields.addshieldstats:
        description: Permission to /addshieldstats
        default: op
        