name: AbsorptionShields
version: ${project.version}
website: http://robomwm.com
author: RoboMWM
main: com.robomwm.absorptionshields.AbsorptionShields
softdepend:
- CrackShot
- ExtraHardMode
- MLGDamageIndicators
depend:
- CustomItemRecipes
commands:
  addshieldstats:
      description: Gives you the specified shield
      permission: absorptionshields.addshieldstats
      permission-message: Hmm, this command isn't for you.
permissions:
    absorptionshields.*:
        description: Grants ALL THE THINGS
        children:
            absorptionshields.addshieldstats: true
    absorptionshields.addshieldstats:
        description: Permission to /addshieldstats
        default: op
        